name: 'Checkout and npm install'
description: 'This action checks out the commit, sets up Node and installs deps using npm.'
author: 'yoobic'
inputs:
  fetch-depth:
    required: false
    description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
    default: '1'
  token:
    required: false
    description: 'Personal access token (PAT) used to fetch the repository.'
    default: ${{ github.token }}
  gcp_credentials:
    required: false
    description: 'The google credentials'
  include_master:
    required: false
    description: 'Include also master branch in order to do incremental test only on changes'
    default: 'false'
  install:
    required: false
    description: 'If true will run npm install'
    default: 'true'
  build:
    required: false
    description: 'If true will run npm run build'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout master
      if: ${{ inputs.include_master == 'true' }}
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        ref: master

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        persist-credentials: false

    - name: Google authentication
      uses: google-github-actions/auth@v0.4.0
      if: ${{ inputs.gcp_credentials }}
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: Setting up the execution env
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: ./node_modules
        #key: modules-
        key: modules-${{ hashFiles('package-lock.json') }}
        #restore-keys: modules-

    - name: Cache pulumi
      id: cache-pulumi
      uses: actions/cache@v2
      with:
        path: ~/.pulumi
        #key: pulumi-
        key: pulumi-${{ hashFiles('package-lock.json') }}
        #restore-keys: pulumi-

    - name: Cache eslint
      id: cache-eslint
      uses: actions/cache@v2
      with:
        path: ./.eslintcache
        key: eslint-
        restore-keys: eslint-

    - name: Configure gcp artifact
      if: ${{ inputs.gcp_credentials }}
      run: npx google-artifactregistry-auth
      shell: bash

    - name: Install dependencies
      if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' && inputs.install == 'true' }}
      run: npm install # ci --ignore-script
      shell: bash

    - name: Build
      if: ${{ inputs.build == 'true' }}
      run: npm run build --if-present
      shell: bash
